const tradeData = [
    { name: "ADVENTURE TOURISM & TREKKING OPERATOR", type: "GTL", code: "902" },
    { name: "ADVERTISING, IT SERVICES & PUBLICATION", type: "GTL", code: "942" },
    { name: "AGRICULTURAL BROKERAGE & LIVESTOCK SUPPLY", type: "GTL", code: "999" },
    { name: "AGRICULTURAL CHEMICALS & FERTILIZERS", type: "GTL", code: "998" },
    { name: "AGRICULTURE & FARMING PRODUCT", type: "GTL", code: "997" },
    { name: "ALMIRAH MFG", type: "ITL", code: "9806" },
    { name: "ALUMINIUM DOOR & WINDOW", type: "ITL", code: "9797" },
    { name: "ALUMINIUM FABRICATION", type: "ITL", code: "9796" },
    { name: "ANIMAL NUTRITION & SUPPLEMENTS", type: "GTL", code: "996" },
    { name: "ARCHITECTURE & DESIGN SERVICES", type: "GTL", code: "995" },
    { name: "ART & CRAFT", type: "GTL", code: "889" },
    { name: "ASTROLOGY & SPIRITUAL CONSULTANCY", type: "GTL", code: "884" },
    { name: "ATTA CHAKKI", type: "ITL", code: "9682" },
    { name: "ATTA PACKAGING AND FLOUR MILL", type: "ITL", code: "9679" },
    { name: "AUTO & BIKE PARTS", type: "GTL", code: "888" },
    { name: "AUTOMOTIVE SALES & DEALERSHIP", type: "GTL", code: "994" },
    { name: "AYURVEDIC MEDICINE MFG", type: "ITL", code: "9590" },
    { name: "BAG MATERIAL MFG AND SALE", type: "ITL", code: "9569" },
    { name: "BAKERY & CONFECTIONERY", type: "GTL", code: "993" },
    { name: "BAKERY ITEM SELLING COUNTER (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9548" },
    { name: "BAKERY ITEM SELLING COUNTER (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9547" },
    { name: "BANKING & FINANCIAL SERVICES", type: "GTL", code: "992" },
    { name: "BANQUET HALL HAVING 101 TO 150 SEATS CAPACITIES AT A TIME", type: "HTL", code: "9526" },
    { name: "BANQUET HALL HAVING 151 SEATS AND ABOVE AT A TIME", type: "HTL", code: "9525" },
    { name: "BANQUET HALL HAVING 51 TO 100 SEATS CAPACITIES AT A TIME", type: "HTL", code: "9524" },
    { name: "BANQUET HALL HAVING UPTO 50 SEATS CAPACITIES AT A TIME", type: "HTL", code: "9523" },
    { name: "BAR BENDED WIRE", type: "ITL", code: "9520" },
    { name: "BATTERIES & AUTO COMPONENTS", type: "GTL", code: "890" },
    { name: "BATTERIES & AUTO COMPONENTS", type: "GTL", code: "968" },
    { name: "BEAUTY PARLOUR OR SALON (LADIES AND KIDS) WITH SPA OR OTHER SERVICES", type: "HTL", code: "9486" },
    { name: "BEAUTY PARLOUR OR SALON (LADIES AND KIDS) WITHOUT SPA OR OTHER SERVICES", type: "HTL", code: "9485" },
    { name: "BHOJANALAYA HAVING 16 SEATS TO 30 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9459" },
    { name: "BHOJANALAYA HAVING 16 SEATS TO 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9458" },
    { name: "BHOJANALAYA HAVING ABOVE 30 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9457" },
    { name: "BHOJANALAYA HAVING ABOVE 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9456" },
    { name: "BHOJANALAYA HAVING UP TO 15 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9461" },
    { name: "BHOJANALAYA HAVING UP TO 15 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9460" },
    { name: "BIBAH BHAWAN HAVING 101 TO 150 SEATS CAPACITIES AT A TIME", type: "HTL", code: "9454" },
    { name: "BIBAH BHAWAN HAVING 151 SEATS AND ABOVE AT A TIME", type: "HTL", code: "9453" },
    { name: "BIBAH BHAWAN HAVING 51 TO 100 SEATS CAPACITIES AT A TIME", type: "HTL", code: "9452" },
    { name: "BIBAH BHAWAN UPTO 50 SEATS CAPACITIES AT A TIME", type: "HTL", code: "9451" },
    { name: "BICYLE & FITNESS EQUIPMENT", type: "GTL", code: "886" },
    { name: "BINDING PRESS", type: "ITL", code: "9423" },
    { name: "BIO PESTICIDES", type: "GTL", code: "991" },
    { name: "BLOOD BANK", type: "HTL", code: "9395" },
    { name: "BLOOD COLLECTION CENTRE (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9394" },
    { name: "BLOOD COLLECTION CENTRE (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9393" },
    { name: "BOARD FURNITURE", type: "ITL", code: "9391" },
    { name: "BODY CONSTRUCTION", type: "ITL", code: "9390" },
    { name: "BODY GARAGE", type: "ITL", code: "9389" },
    { name: "BODY REPAIRING", type: "ITL", code: "9387" },
    { name: "BODY REPAIRING AND SUPPLY", type: "ITL", code: "9386" },
    { name: "BOOK & STATIONARY & GIFT ITEMS", type: "GTL", code: "911" },
    { name: "BOUTIQUE TAILORING", type: "GTL", code: "990" },
    { name: "BRICK BLOCKS", type: "ITL", code: "9313" },
    { name: "BROKERAGE & CONSULTANCY SERVICES", type: "GTL", code: "989" },
    { name: "BUILDING MATERIALS", type: "GTL", code: "988" },
    { name: "C & F (CARRYING & FORWARDING)", type: "GTL", code: "883" },
    { name: "C I SHEET CORRUGATION", type: "ITL", code: "9194" },
    { name: "CABLE & TRANSFORMERS", type: "ITL", code: "9185" },
    { name: "CAFE (AIR CONDITIONED ESTABLISHMENT WITH ANY SEATING CAPACITY)", type: "HTL", code: "9163" },
    { name: "CAFE HAVING 16 SEATS TO 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9162" },
    { name: "CAFE HAVING ABOVE 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9161" },
    { name: "CAFE HAVING UP TO 15 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "9160" },
    { name: "CANDLE MFG", type: "ITL", code: "9148" },
    { name: "CAR SERVICING (5 K.W)", type: "ITL", code: "9109" },
    { name: "CAR SERVICING CENTRE(48 KW)", type: "ITL", code: "9108" },
    { name: "CAR WASHING CENTRE", type: "ITL", code: "9104" },
    { name: "CAR WORKSHOP", type: "ITL", code: "9100" },
    { name: "CAROM MAKING (4 KW)", type: "ITL", code: "9074" },
    { name: "CATERING SERVICE", type: "HTL", code: "9055" },
    { name: "CEMENT, CONCRETE, ADMIXTURE", type: "ITL", code: "9015" },
    { name: "CHAIR ASSEMBLING", type: "ITL", code: "9009" },
    { name: "CHAIR TABLE ASSEMBLING", type: "ITL", code: "9007" },
    { name: "CHARTERED ACCOUNTANTS FIRM", type: "GTL", code: "987" },
    { name: "CHAT HOUSE (AIR CONDITIONED ESTABLISHMENT) NO SEATING ARRANGEMENT", type: "HTL", code: "9000" },
    { name: "CHAT HOUSE (NON AIR CONDITIONED ESTABLISHMENT) NO SEATING ARRANGEMENT", type: "HTL", code: "8999" },
    { name: "CHAT HOUSE HAVING 16 SEATS TO 30 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "8998" },
    { name: "CHAT HOUSE HAVING 16 SEATS TO 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "8997" },
    { name: "CHAT HOUSE HAVING ABOVE 30 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "8996" },
    { name: "CHAT HOUSE HAVING ABOVE 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "8995" },
    { name: "CHAT HOUSE HAVING UP TO 15 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "8994" },
    { name: "CHAT HOUSE HAVING UP TO 15 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "8993" },
    { name: "CHILDCARE & EDUCATION SERVICES", type: "GTL", code: "986" },
    { name: "CLINIC AND RESEARCH CENTRE(AYURBEDIC/AYUSH)", type: "HTL", code: "8935" },
    { name: "CLOUD KITCHEN (TAKE AWAY COUNTER)", type: "HTL", code: "8855" },
    { name: "COIR BLOCKS MFG", type: "ITL", code: "8819" },
    { name: "COKE BREEDGE MFG UNIT", type: "ITL", code: "8815" },
    { name: "COLOUR COATED ROOFING SHEETS", type: "ITL", code: "8802" },
    { name: "COMMUNITY HALL HAVING 101 TO 150 SEATS CAPACITIES AT A TIME", type: "HTL", code: "8768" },
    { name: "COMMUNITY HALL HAVING 151 SEATS AND ABOVE AT A TIME", type: "HTL", code: "8767" },
    { name: "COMMUNITY HALL HAVING 51 TO 100 SEATS CAPACITIES AT A TIME", type: "HTL", code: "8766" },
    { name: "COMMUNITY HALL UPTO 50 SEATS CAPACITIES AT A TIME", type: "HTL", code: "8765" },
    { name: "COMPANY CORRESPONDENCE & IT MANAGEMENT OFFICE", type: "GTL", code: "985" },
    { name: "COMPUTER SALE & SERVICE", type: "GTL", code: "984" },
    { name: "CONFECTIONARY", type: "GTL", code: "881" },
    { name: "CONFERENCE HALL HAVING 101 TO 150 SEATS CAPACITIES AT A TIME", type: "HTL", code: "8562" },
    { name: "CONFERENCE HALL HAVING 151 SEATS AND ABOVE AT A TIME", type: "HTL", code: "8561" },
    { name: "CONFERENCE HALL HAVING 51 TO 100 SEATS CAPACITIES AT A TIME", type: "HTL", code: "8560" },
    { name: "CONFERENCE HALL UPTO 50 SEATS CAPACITIES AT A TIME", type: "HTL", code: "8559" },
    { name: "CONSTRUCTION & SUPPLY", type: "GTL", code: "983" },
    { name: "CONSTRUCTION, REAL ESTATE & DESIGN SERVICES", type: "GTL", code: "982" },
    { name: "CONSUMER ELECTRONICS & APPLIANCE RETAIL", type: "GTL", code: "981" },
    { name: "CONTRACT & SUPPLY", type: "GTL", code: "874" },
    { name: "CONVERSION OF PULP SHEET", type: "ITL", code: "8286" },
    { name: "CORROGATED CARTOONS & SHEET MFG", type: "ITL", code: "8273" },
    { name: "CROCKERY & RELATED", type: "GTL", code: "822" },
    { name: "CRUSHER MACHINE", type: "ITL", code: "8141" },
    { name: "CULTURAL & TOURISM SERVICES", type: "GTL", code: "980" },
    { name: "CYBER CAFE (INTERNET)", type: "GTL", code: "979" },
    { name: "DAIRY PRODUCTS", type: "GTL", code: "978" },
    { name: "DALMUNG BHUJIA MFG", type: "ITL", code: "8083" },
    { name: "DANCE CLASS AND TRAINING", type: "GTL", code: "977" },
    { name: "DENTAL CLINIC (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "8039" },
    { name: "DENTAL CLINIC (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "8038" },
    { name: "DENTAL MATERIALS & EQUIPMENTS", type: "GTL", code: "976" },
    { name: "DEPARTMENTAL STORE", type: "GTL", code: "975" },
    { name: "DHABA HAVING 16 SEATS TO 30 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7986" },
    { name: "DHABA HAVING 16 SEATS TO 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7985" },
    { name: "DHABA HAVING ABOVE 30 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7984" },
    { name: "DHABA HAVING ABOVE 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7983" },
    { name: "DHABA HAVING UP TO 15 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7982" },
    { name: "DHABA HAVING UP TO 15 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7981" },
    { name: "DIAGNOSTIC CENTRE", type: "HTL", code: "7975" },
    { name: "DIESEL PUMP", type: "ITL", code: "7962" },
    { name: "DIESEL PUMP REPAIRING", type: "ITL", code: "7932" },
    { name: "DIESEL SERVICE", type: "ITL", code: "7958" },
    { name: "DISPOSAL PAPER PLATE", type: "ITL", code: "7913" },
    { name: "DISTRIBUTOR", type: "GTL", code: "879" },
    { name: "DOCTOR'S CHAMBER (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7832" },
    { name: "DOCTOR'S CHAMBER (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7831" },
    { name: "DOCTOR'S CLINIC (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7829" },
    { name: "DOCTOR'S CLINIC (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7828" },
    { name: "DOCTOR'S CLINIC (HEMATOLOGICAL)", type: "HTL", code: "7827" },
    { name: "DOOR MANUFACTURE", type: "ITL", code: "7822" },
    { name: "DRILL MACHINE", type: "ITL", code: "7812" },
    { name: "DRY CLEANERS", type: "ITL", code: "7790" },
    { name: "E RICKSHAW BODY MANUFACTURING", type: "ITL", code: "7746" },
    { name: "E-COMMERCE & ONLINE TRADE SERVICES", type: "GTL", code: "974" },
    { name: "E-RICKSHAW MFG", type: "ITL", code: "7377" },
    { name: "EDUCATIONAL SERVICES", type: "GTL", code: "973" },
    { name: "ELECTRICAL CONTRACT AND SUPPLY", type: "GTL", code: "972" },
    { name: "ELECTRODES", type: "ITL", code: "7509" },
    { name: "ELECTRONICS DEVICE & REPAIR SERVICES", type: "GTL", code: "971" },
    { name: "ENVIRONMENTAL AND GREEN SOLUTIONS SERVICES", type: "GTL", code: "969" },
    { name: "EX. BOOK BINDING", type: "ITL", code: "7350" },
    { name: "EXERCISE BOOK AND REGISTER MFG", type: "ITL", code: "7348" },
    { name: "EXERCISE BOOK BONDING", type: "ITL", code: "7347" },
    { name: "EXERCISE BOOK PAPER", type: "ITL", code: "7346" },
    { name: "FABRICATION", type: "ITL", code: "7331" },
    { name: "FABRICATION (9 H.P)", type: "ITL", code: "7327" },
    { name: "FABRICATION & LATH", type: "ITL", code: "7330" },
    { name: "FABRICATION & MANUFACTURING", type: "ITL", code: "7329" },
    { name: "FABRICATION OF WINDOWS, GILL, GATE", type: "ITL", code: "7326" },
    { name: "FABRICATION OFFICE", type: "GTL", code: "967" },
    { name: "FABRICATION REPAIRING WORKS MFG", type: "ITL", code: "7324" },
    { name: "FACTORISES 0 HP TO 4 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "7319" },
    { name: "FACTORISES 0 HP TO 4 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "7318" },
    { name: "FACTORISES 0 HP TO 4 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "7317" },
    { name: "FACTORISES 0 HP TO 4 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "7316" },
    { name: "FACTORISES 0 HP TO 4 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "7315" },
    { name: "FACTORISES 0 HP TO 4 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "7314" },
    { name: "FACTORISES 101 HP TO 250 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "7313" },
    { name: "FACTORISES 101 HP TO 250 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "7312" },
    { name: "FACTORISES 101 HP TO 250 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "7311" },
    { name: "FACTORISES 101 HP TO 250 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "7310" },
    { name: "FACTORISES 101 HP TO 250 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "7309" },
    { name: "FACTORISES 101 HP TO 250 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "7308" },
    { name: "FACTORISES 11 HP TO 19 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "7307" },
    { name: "FACTORISES 11 HP TO 19 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "7306" },
    { name: "FACTORISES 11 HP TO 19 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "7305" },
    { name: "FACTORISES 11 HP TO 19 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "7304" },
    { name: "FACTORISES 11 HP TO 19 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "7303" },
    { name: "FACTORISES 11 HP TO 19 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "7302" },
    { name: "FACTORISES 20 HP TO 100 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "7301" },
    { name: "FACTORISES 20 HP TO 100 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "7300" },
    { name: "FACTORISES 20 HP TO 100 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "7299" },
    { name: "FACTORISES 20 HP TO 100 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "7298" },
    { name: "FACTORISES 20 HP TO 100 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "7297" },
    { name: "FACTORISES 20 HP TO 100 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "7296" },
    { name: "FACTORISES 251 HP & ABOVE WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "7295" },
    { name: "FACTORISES 251 HP & ABOVE WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "7294" },
    { name: "FACTORISES 251 HP & ABOVE WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "7293" },
    { name: "FACTORISES 251 HP & ABOVE WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "7292" },
    { name: "FACTORISES 251 HP & ABOVE WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "7291" },
    { name: "FACTORISES 251 HP & ABOVE WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "7290" },
    { name: "FACTORISES 5 HP TO 10 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "7289" },
    { name: "FACTORISES 5 HP TO 10 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "7288" },
    { name: "FACTORISES 5 HP TO 10 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "7287" },
    { name: "FACTORISES 5 HP TO 10 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "7320" },
    { name: "FACTORISES 5 HP TO 10 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "7286" },
    { name: "FACTORISES 5 HP TO 10 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "7285" },
    { name: "FACTORISES,WORKSHOP, MANUFACTURING UNIT ETC. 11 HP TO 19 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "7284" },
    { name: "FAIR PRICE SHOP", type: "STL", code: "748" },
    { name: "FAN ASSEMBLING AND SALE", type: "ITL", code: "7277" },
    { name: "FAST FOOD HAVING 16 SEATS TO 30 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7263" },
    { name: "FAST FOOD HAVING 16 SEATS TO 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7262" },
    { name: "FAST FOOD HAVING ABOVE 30 SEATS", type: "HTL", code: "7261" },
    { name: "FAST FOOD HAVING UP TO 15 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7260" },
    { name: "FAST FOOD HAVING UP TO 15 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "7259" },
    { name: "FEBRICATION", type: "ITL", code: "7257" },
    { name: "FILM, TV & MULTIMEDIA PRODUCTION SERVICES", type: "GTL", code: "966" },
    { name: "FIRE SAFETY SERVICES", type: "GTL", code: "877" },
    { name: "FLEX PRINTING", type: "ITL", code: "7185" },
    { name: "FLEXIBLE LAMINATE", type: "ITL", code: "7179" },
    { name: "FMCG DISTRIBUTORS", type: "GTL", code: "965" },
    { name: "FMCG GOODS SALE", type: "GTL", code: "964" },
    { name: "FOAM MANUFACTURE", type: "ITL", code: "7135" },
    { name: "FOOD & BEVERAGE SERVICES", type: "GTL", code: "963" },
    { name: "FOOD PROCESSING AND PACKAGING", type: "ITL", code: "7113" },
    { name: "FOOD PROCESSING,PACKAGING", type: "ITL", code: "7110" },
    { name: "FOOD PROCESSING,PACKAGING AND TRADING", type: "ITL", code: "7109" },
    { name: "FOUNDRY SPARE PARTS", type: "ITL", code: "7084" },
    { name: "FRUITS AND NON FRUITS BEVERAGES & FLAVOUR DRINKS", type: "ITL", code: "7057" },
    { name: "FRUITS AND NON FRUITS BEVERAGES AND FLAVOURED DRINKS", type: "ITL", code: "7056" },
    { name: "FURNACE", type: "ITL", code: "7043" },
    { name: "FURNISHING ITEMS", type: "ITL", code: "7036" },
    { name: "FURNITURE MFG", type: "ITL", code: "7013" },
    { name: "GARAGE", type: "ITL", code: "6989" },
    { name: "GARMENTS MANUFACTURING", type: "ITL", code: "6966" },
    { name: "GAS AGENCY", type: "GTL", code: "876" },
    { name: "GATE GRILL & FABRICATION", type: "ITL", code: "6940" },
    { name: "GEMS AND JEWELLERY", type: "GTL", code: "962" },
    { name: "GENERAL SUPPLY & STATIONARY SERVICES", type: "GTL", code: "875" },
    { name: "GLASS CUTTING", type: "ITL", code: "6846" },
    { name: "GLASS MARBLE", type: "ITL", code: "6840" },
    { name: "GLASS SHOWCASE MFG", type: "ITL", code: "6836" },
    { name: "GRILL", type: "ITL", code: "6734" },
    { name: "GRINDING GOODS PACKAGING", type: "ITL", code: "6731" },
    { name: "GRINDING MINI MILL", type: "ITL", code: "6730" },
    { name: "GROCERY ITEM", type: "GTL", code: "961" },
    { name: "GROCERY ITEM PACKAGING", type: "ITL", code: "6690" },
    { name: "GUEST HOUSE HAVING 16 BEDS TO 30 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6667" },
    { name: "GUEST HOUSE HAVING 16 BEDS TO 30 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6666" },
    { name: "GUEST HOUSE HAVING UP TO 15 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6665" },
    { name: "GUEST HOUSE HAVING UP TO 15 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6664" },
    { name: "GYMNASIUM", type: "HTL", code: "6658" },
    { name: "GYPSUM FALSE CELLING MFG", type: "ITL", code: "6657" },
    { name: "H B WIRE AND BELTS MFG", type: "ITL", code: "6656" },
    { name: "HANDLOOM & HANDICRAFT", type: "GTL", code: "873" },
    { name: "HARD BOARD MAKING", type: "ITL", code: "6602" },
    { name: "HARDWARE", type: "GTL", code: "960" },
    { name: "HARDWARE & TOOLS", type: "GTL", code: "959" },
    { name: "HEALTH INSTITUTION", type: "HTL", code: "2654" },
    { name: "HEALTHCARE & MEDICAL SUPPLIES", type: "GTL", code: "958" },
    { name: "HERBAL & NATURAL PRODUCTS", type: "GTL", code: "957" },
    { name: "HOME APPLIANCE RETAIL & REPAIR", type: "GTL", code: "956" },
    { name: "HOME DECOR & FLORAL PRODUCTS", type: "GTL", code: "955" },
    { name: "HOMEO CLINIC", type: "HTL", code: "6487" },
    { name: "HOMESTAY HAVING 16 BEDS TO 30 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6484" },
    { name: "HOMESTAY HAVING 16 BEDS TO 30 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6483" },
    { name: "HOMESTAY HAVING UP TO 15 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6482" },
    { name: "HOMESTAY HAVING UP TO 15 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6481" },
    { name: "HORTICULTURAL SERVICES / NURSERY AND GARDENING", type: "GTL", code: "954" },
    { name: "HOSPITAL HAVING 16 BEDS TO 30 BEDS", type: "HTL", code: "6466" },
    { name: "HOSPITAL HAVING ABOVE 30 BEDS", type: "HTL", code: "6465" },
    { name: "HOSPITAL HAVING UP TO 15 BEDS", type: "HTL", code: "6464" },
    { name: "HOSTEL HAVING 101 BEDS TO 150 BEDS", type: "HTL", code: "6460" },
    { name: "HOSTEL HAVING 16 BEDS TO 30 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6457" },
    { name: "HOSTEL HAVING 16 BEDS TO 30 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6456" },
    { name: "HOSTEL HAVING 31 BEDS TO 50 BEDS", type: "HTL", code: "6455" },
    { name: "HOSTEL HAVING 51 BEDS TO 100 BEDS", type: "HTL", code: "6459" },
    { name: "HOSTEL HAVING ABOVE 151 BEDS", type: "HTL", code: "6458" },
    { name: "HOSTEL HAVING UP TO 15 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6453" },
    { name: "HOSTEL HAVING UP TO 15 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6452" },
    { name: "HOTEL HAVING 101 BEDS TO 150 BEDS", type: "HTL", code: "6451" },
    { name: "HOTEL HAVING 16 BEDS TO 30 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6449" },
    { name: "HOTEL HAVING 16 BEDS TO 30 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6448" },
    { name: "HOTEL HAVING 31 BEDS TO 50 BEDS", type: "HTL", code: "6447" },
    { name: "HOTEL HAVING 51 BEDS TO 100 BEDS", type: "HTL", code: "6450" },
    { name: "HOTEL HAVING ABOVE 151 BEDS", type: "HTL", code: "6446" },
    { name: "HOTEL HAVING UP TO 15 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6445" },
    { name: "HOTEL HAVING UP TO 15 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6444" },
    { name: "HSD FILLING STATION", type: "ITL", code: "6412" },
    { name: "ICE CREAM PARLOUR (AIR CONDITIONED ESTABLISHMENT WITH ANY SEATING CAPACITY)", type: "HTL", code: "6395" },
    { name: "ICE CREAM PARLOUR (NON AIR CONDITIONED ESTABLISHMENT) NO SEATING ARRANGEMENT", type: "HTL", code: "6394" },
    { name: "ICE CREAM PARLOUR HAVING 16 SEATS TO 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6393" },
    { name: "ICE CREAM PARLOUR HAVING ABOVE 30 SEATS", type: "HTL", code: "6392" },
    { name: "ICE CREAM PARLOUR HAVING UP TO 15 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6391" },
    { name: "IMFL 'ON' HOTEL", type: "HTL", code: "6378" },
    { name: "IMFL BAR CUM RESTAURANT", type: "HTL", code: "6382" },
    { name: "IMFL WINE RETAIL SHOP", type: "GTL", code: "953" },
    { name: "INDRACOT OIL PRODUCTS", type: "ITL", code: "6355" },
    { name: "INDUSTRIAL SUPPLIES", type: "GTL", code: "952" },
    { name: "INFORMATION TECHNOLOGY & SUPPORT SERVICES", type: "GTL", code: "951" },
    { name: "IRON FABRICATION", type: "ITL", code: "6271" },
    { name: "IRON SCRAP CUTTING MACHINE", type: "ITL", code: "6260" },
    { name: "IT (INFORMATION TECHNOLOGY)", type: "GTL", code: "950" },
    { name: "IVF CENTRE HAVING 16 BEDS TO 30 BEDS", type: "HTL", code: "6217" },
    { name: "IVF CENTRE HAVING ABOVE 30 BEDS", type: "HTL", code: "6216" },
    { name: "IVF CENTRE HAVING UP TO 15 BEDS", type: "HTL", code: "6215" },
    { name: "JOB CONSULTANT PLACEMENT SERVICE", type: "GTL", code: "949" },
    { name: "JUICE CORNER (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6187" },
    { name: "JUICE CORNER (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6186" },
    { name: "JUTE FABRICS(71 HP)", type: "ITL", code: "6182" },
    { name: "JUTE YARN MFG (239 HP)", type: "ITL", code: "6178" },
    { name: "LATH JOB WORKS", type: "ITL", code: "6094" },
    { name: "LATH MACHINE", type: "ITL", code: "6093" },
    { name: "LATH MACHINE REPAIRING", type: "ITL", code: "6092" },
    { name: "LATH WORKS", type: "ITL", code: "6091" },
    { name: "LATH WORKS 7 K.W (9.31 H.P)", type: "ITL", code: "6088" },
    { name: "LEATHER PRODUCTS & ACCESSORIES", type: "GTL", code: "948" },
    { name: "LIME PACKAGING(3 KW)", type: "ITL", code: "6053" },
    { name: "LOADING CUM UNLOADING", type: "ITL", code: "6045" },
    { name: "LODGE HAVING 101 BEDS TO 150 BEDS", type: "HTL", code: "6043" },
    { name: "LODGE HAVING 16 BEDS TO 30 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6040" },
    { name: "LODGE HAVING 16 BEDS TO 30 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6039" },
    { name: "LODGE HAVING 31 BEDS TO 50 BEDS", type: "HTL", code: "6038" },
    { name: "LODGE HAVING 51 BEDS TO 100 BEDS", type: "HTL", code: "6042" },
    { name: "LODGE HAVING ABOVE 151 BEDS", type: "HTL", code: "6041" },
    { name: "LODGE HAVING UP TO 15 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6037" },
    { name: "LODGE HAVING UP TO 15 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "6036" },
    { name: "LOZENGE", type: "ITL", code: "6024" },
    { name: "LUBRICANT", type: "ITL", code: "6018" },
    { name: "M.S BLACK PIPES, GI PIPES, ST POLES", type: "ITL", code: "5993" },
    { name: "M.S.FLAT- CLAMPS(20 H.P)", type: "ITL", code: "5992" },
    { name: "MACHINARY RELATED", type: "GTL", code: "821" },
    { name: "MACHINERY GOODS", type: "ITL", code: "5973" },
    { name: "MACHINERY GOODS MFG", type: "ITL", code: "5972" },
    { name: "MACHINERY PARTS REPAIR", type: "ITL", code: "5964" },
    { name: "MAKEUP STUDIO TRAINING IN MAKEUP ARTIST COURSE", type: "GTL", code: "947" },
    { name: "MANPOWER SERVICES", type: "GTL", code: "816" },
    { name: "MANUFACTURE OF ELECTRICAL APPARATUS", type: "ITL", code: "5928" },
    { name: "MANUFACTURE OF ELECTRODES", type: "ITL", code: "5927" },
    { name: "MANUFACTURING", type: "GTL", code: "820" },
    { name: "MANUFACTURING OF PVC PIPE AND FITTING", type: "ITL", code: "5903" },
    { name: "MANUFACTURING PHENYL", type: "ITL", code: "5937" },
    { name: "MANUFACTURING UNIT (OFFICE)", type: "GTL", code: "946" },
    { name: "MANUFACTURING UNIT 0 HP TO 4 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "5899" },
    { name: "MANUFACTURING UNIT 0 HP TO 4 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "5881" },
    { name: "MANUFACTURING UNIT 0 HP TO 4 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "5880" },
    { name: "MANUFACTURING UNIT 0 HP TO 4 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "5879" },
    { name: "MANUFACTURING UNIT 0 HP TO 4 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "5878" },
    { name: "MANUFACTURING UNIT 0 HP TO 4 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "5877" },
    { name: "MANUFACTURING UNIT 101 HP TO 250 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "5876" },
    { name: "MANUFACTURING UNIT 101 HP TO 250 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "5898" },
    { name: "MANUFACTURING UNIT 101 HP TO 250 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "5897" },
    { name: "MANUFACTURING UNIT 101 HP TO 250 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "5896" },
    { name: "MANUFACTURING UNIT 101 HP TO 250 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "5895" },
    { name: "MANUFACTURING UNIT 101 HP TO 250 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "5894" },
    { name: "MANUFACTURING UNIT 11 HP TO 19 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "5875" },
    { name: "MANUFACTURING UNIT 11 HP TO 19 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "5893" },
    { name: "MANUFACTURING UNIT 11 HP TO 19 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "5874" },
    { name: "MANUFACTURING UNIT 11 HP TO 19 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "5892" },
    { name: "MANUFACTURING UNIT 11 HP TO 19 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "5873" },
    { name: "MANUFACTURING UNIT 20 HP TO 100 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "5872" },
    { name: "MANUFACTURING UNIT 20 HP TO 100 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "5891" },
    { name: "MANUFACTURING UNIT 20 HP TO 100 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "5871" },
    { name: "MANUFACTURING UNIT 20 HP TO 100 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "5890" },
    { name: "MANUFACTURING UNIT 20 HP TO 100 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "5889" },
    { name: "MANUFACTURING UNIT 20 HP TO 100 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "5888" },
    { name: "MANUFACTURING UNIT 251 HP & ABOVE WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "5887" },
    { name: "MANUFACTURING UNIT 251 HP & ABOVE WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "5870" },
    { name: "MANUFACTURING UNIT 251 HP & ABOVE WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "5869" },
    { name: "MANUFACTURING UNIT 251 HP & ABOVE WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "5868" },
    { name: "MANUFACTURING UNIT 251 HP & ABOVE WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "5886" },
    { name: "MANUFACTURING UNIT 251 HP & ABOVE WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "5885" },
    { name: "MANUFACTURING UNIT 5 HP TO 10 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "5867" },
    { name: "MANUFACTURING UNIT 5 HP TO 10 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "5866" },
    { name: "MANUFACTURING UNIT 5 HP TO 10 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "ITL", code: "5884" },
    { name: "MANUFACTURING UNIT 5 HP TO 10 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "5883" },
    { name: "MANUFACTURING UNIT 5 HP TO 10 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "5865" },
    { name: "MANUFACTURING UNIT 5 HP TO 10 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "5864" },
    { name: "MARKETING, ADVERTISING & CONSULTANCY SERVICES", type: "GTL", code: "945" },
    { name: "MCB, RCCB, MOTOR STARTERS", type: "ITL", code: "5801" },
    { name: "MECHANICAL & REPAIRING WORKS OF CAR", type: "ITL", code: "5799" },
    { name: "MECHANICAL WORKS & SERVICING", type: "ITL", code: "5797" },
    { name: "MEDIA & COMMUNICATION", type: "GTL", code: "944" },
    { name: "MEDIA & PUBLISHING", type: "GTL", code: "943" },
    { name: "METAL PRODUCTS & CONSTRUCTION MATERIALS", type: "GTL", code: "941" },
    { name: "MFG AND TRADING DISINFECTANTS, HOME CARE ,INSECTICIDES, PESTICIDES, HERBICIDES", type: "ITL", code: "5682" },
    { name: "MFG AND TRADING OF DISINFECTANTS, HOME CARE,PERSONAL CARE,CAR CARE,INSECTICIDES,PESTICIDES,HERBICIDES", type: "ITL", code: "5681" },
    { name: "MFG OF BAMBOO STICKS", type: "ITL", code: "5679" },
    { name: "MFG OF BISCUITS,P CHIPS, POPCORN,SAVOURY ITEMS", type: "ITL", code: "5678" },
    { name: "MFG OF BRASS ALUMINIUM CIRCLE SHEET", type: "ITL", code: "5677" },
    { name: "MFG OF CHAKKERED TILES", type: "ITL", code: "5676" },
    { name: "MFG OF CLAMPAS", type: "ITL", code: "5675" },
    { name: "MFG OF CORROGATED CARTOON", type: "ITL", code: "5674" },
    { name: "MFG OF IMFL BOTTOLLING", type: "ITL", code: "5671" },
    { name: "MFG OF MATTRESSES , PILLOW, CUSHIONS ETC", type: "ITL", code: "5670" },
    { name: "MFG OF PAINT", type: "ITL", code: "5669" },
    { name: "MFG OF PEVER BLOCKS", type: "ITL", code: "5668" },
    { name: "MFG OF PLASTIC PIPE", type: "ITL", code: "5667" },
    { name: "MFG OF PVC AND RCC PORCUPINE 10 HP", type: "ITL", code: "5666" },
    { name: "MFG OF WOODEN OIL", type: "ITL", code: "5663" },
    { name: "MFG PLASTIC POLYTHENE AND ALKATHENE PIPE", type: "ITL", code: "5661" },
    { name: "MFG ROOFING SELT", type: "ITL", code: "5660" },
    { name: "MFG TYRE RE THREADING MATERIALS", type: "ITL", code: "5659" },
    { name: "MGF. OF PEVER BLOCKS", type: "ITL", code: "5655" },
    { name: "MICRO HARD ELECTRIC", type: "ITL", code: "5651" },
    { name: "MICROBREWERY", type: "HTL", code: "5650" },
    { name: "MILL", type: "ITL", code: "5641" },
    { name: "MINI OFFSET PRINTING PRESS", type: "ITL", code: "5630" },
    { name: "MOLDED ALUMINIUM UTENSILS", type: "ITL", code: "5565" },
    { name: "MORTIN PRODUCT (M F G PLASTIC & CONTANER)", type: "ITL", code: "5557" },
    { name: "MOSQUITO REPELLENT REFILL AND MAT", type: "ITL", code: "5553" },
    { name: "MOSQUITO REPELLENT-INSECTICIDE PAPER, LIQUID DETERGENT, HAIR COLOR(570 HP)", type: "ITL", code: "5552" },
    { name: "MOTOR PARTS REPAIR WITH H.P 4KW", type: "ITL", code: "5508" },
    { name: "MOTOR REPAIRING", type: "ITL", code: "5485" },
    { name: "MOTOR VEHICLE WORKSHOP", type: "ITL", code: "5480" },
    { name: "MOTOR WORKS (H.P 5 K.W)", type: "ITL", code: "5479" },
    { name: "MULTIPLEX CINEMA", type: "GTL", code: "940" },
    { name: "MUSICAL INSTRUMENT", type: "GTL", code: "939" },
    { name: "MUSTARD OIL REPACKING UNIT", type: "ITL", code: "5458" },
    { name: "MUSTERD OIL MFG AND PACKAGING", type: "ITL", code: "5456" },
    { name: "NGO / TRUST OFFICE", type: "GTL", code: "938" },
    { name: "NURSING AND PARAMEDICAL INSTITUTE", type: "HTL", code: "5413" },
    { name: "NURSING HOME HAVING 16 BEDS TO 30 BEDS", type: "HTL", code: "5412" },
    { name: "NURSING HOME HAVING ABOVE 30 BEDS", type: "HTL", code: "5411" },
    { name: "NURSING HOME HAVING UP TO 15 BEDS", type: "HTL", code: "5410" },
    { name: "NURSING SCHOOL", type: "HTL", code: "5409" },
    { name: "NUTRITION FOOD SUPPLEMENT", type: "GTL", code: "937" },
    { name: "OFFICE BASED TRADE", type: "GTL", code: "819" },
    { name: "OPTICAL LENS MAKING", type: "ITL", code: "5175" },
    { name: "OPTICAL RETAIL & REPAIR", type: "GTL", code: "936" },
    { name: "P U F PANEL,STEEL STRUCTURE, PROFILE SHEET(48 K.W)", type: "ITL", code: "5146" },
    { name: "PACKAGED DRINKING WATER MFG", type: "ITL", code: "5139" },
    { name: "PACKAGING", type: "ITL", code: "5136" },
    { name: "PACKAGING & DISPOSABLE GOODS", type: "GTL", code: "935" },
    { name: "PACKAGING OF BLESSING AND PHYNILE", type: "ITL", code: "5118" },
    { name: "PACKERS AND MOVERS", type: "GTL", code: "818" },
    { name: "PAN & RELETED PRODUCT RETAIL", type: "GTL", code: "934" },
    { name: "PAN SHOP", type: "STL", code: "749" },
    { name: "PANEL BOARD", type: "ITL", code: "5056" },
    { name: "PAPER CUTTING PRESS", type: "ITL", code: "5042" },
    { name: "PAPER TRAY", type: "ITL", code: "5029" },
    { name: "PARAMEDICAL SCHOOL", type: "HTL", code: "5019" },
    { name: "PAYING GUEST HAVING 101 BEDS TO 150 BEDS", type: "HTL", code: "5007" },
    { name: "PAYING GUEST HAVING 16 BEDS TO 30 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "5004" },
    { name: "PAYING GUEST HAVING 16 BEDS TO 30 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "5003" },
    { name: "PAYING GUEST HAVING 31 BEDS TO 50 BEDS", type: "HTL", code: "5002" },
    { name: "PAYING GUEST HAVING 51 BEDS TO 100 BEDS", type: "HTL", code: "5006" },
    { name: "PAYING GUEST HAVING ABOVE 151 BEDS", type: "HTL", code: "5005" },
    { name: "PAYING GUEST HAVING UP TO 15 BEDS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "5001" },
    { name: "PAYING GUEST HAVING UP TO 15 BEDS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "5000" },
    { name: "PERFUME COMPOUND", type: "ITL", code: "4995" },
    { name: "PERSONAL CARE PRODUCTS OR HOUSEHOLD PRODUCTES", type: "GTL", code: "933" },
    { name: "PET CARE & RETAIL SERVICES", type: "GTL", code: "932" },
    { name: "PETROL PUMP", type: "ITL", code: "4971" },
    { name: "PHARMACEUTICAL & MEDICAL SUPPLY", type: "GTL", code: "931" },
    { name: "PHARMACY RETAIL", type: "GTL", code: "930" },
    { name: "PHENYL", type: "ITL", code: "4954" },
    { name: "PHOTOGRAPHY SERVICES", type: "GTL", code: "929" },
    { name: "PHYSIOTHERAPY ( AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "4928" },
    { name: "PHYSIOTHERAPY (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "4927" },
    { name: "PIPE MFG", type: "ITL", code: "4922" },
    { name: "PLASTIC DOOR MAKING", type: "ITL", code: "4904" },
    { name: "PLASTIC GOOD PRODUCT", type: "ITL", code: "4897" },
    { name: "PLASTIC GRANUALS (40 K.W)", type: "ITL", code: "4883" },
    { name: "PLASTIC ITEMS", type: "GTL", code: "817" },
    { name: "PLASTIC MOSQUITO NET MFG.", type: "ITL", code: "4871" },
    { name: "PLASTIC PACKAGING PRODUCT", type: "ITL", code: "4868" },
    { name: "PLASTIC PRODUCT", type: "ITL", code: "4863" },
    { name: "PLASTIC THREAD", type: "ITL", code: "4856" },
    { name: "PLUG AND PREPLUG", type: "ITL", code: "4845" },
    { name: "POLYCLINIC HAVING 16 BEDS TO 30 BEDS", type: "HTL", code: "4792" },
    { name: "POLYCLINIC HAVING ABOVE 30 BEDS", type: "HTL", code: "4791" },
    { name: "POLYCLINIC HAVING UP TO 15 BEDS", type: "HTL", code: "4790" },
    { name: "POLYCLINIC WITH DAY CARE FACILITY ONLY WITH UPTO 15 BEDS", type: "HTL", code: "4789" },
    { name: "POLYCLINIC WITH NO BED", type: "HTL", code: "4788" },
    { name: "POLYMERS", type: "ITL", code: "4784" },
    { name: "PRESS & MFG OF NOTE BOOKS", type: "ITL", code: "4754" },
    { name: "PRESS 5KW", type: "ITL", code: "4752" },
    { name: "PRINTING & BINDING", type: "ITL", code: "4741" },
    { name: "PRINTING & PUBLISHING SERVICES", type: "GTL", code: "928" },
    { name: "PROFESSIONAL CONSULTANCY SERVICES", type: "GTL", code: "927" },
    { name: "PROFILING ROOFING SHEET", type: "ITL", code: "4676" },
    { name: "PSC POLES", type: "ITL", code: "4665" },
    { name: "PUB", type: "HTL", code: "4663" },
    { name: "PUMP REPAIRING", type: "ITL", code: "4641" },
    { name: "RADIO BROADCASTING SERVICES", type: "GTL", code: "926" },
    { name: "REAL ESTATE SERVICES", type: "GTL", code: "925" },
    { name: "RECYCLING & SCRAP MATERIALS", type: "GTL", code: "924" },
    { name: "REFRIGERATION, FABRICATION AND REPAIRING & SALES", type: "ITL", code: "4454" },
    { name: "RELIGIOUS ARTIFACT PRODUCTION", type: "GTL", code: "923" },
    { name: "RENEWABLE ENERGY & INSTALLATION SERVICES", type: "GTL", code: "922" },
    { name: "RESTAURANT HAVING 16 SEATS TO 30 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "4412" },
    { name: "RESTAURANT HAVING 16 SEATS TO 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "4411" },
    { name: "RESTAURANT HAVING ABOVE 30 SEATS", type: "HTL", code: "4410" },
    { name: "RESTAURANT HAVING UP TO 15 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "4409" },
    { name: "RESTAURANT HAVING UP TO 15 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "4408" },
    { name: "RETAIL - APPAREL & ACCESSORIES", type: "GTL", code: "921" },
    { name: "RICE HOTEL HAVING 16 SEATS TO 30 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "4349" },
    { name: "RICE HOTEL HAVING 16 SEATS TO 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "4348" },
    { name: "RICE HOTEL HAVING ABOVE 30 SEATS", type: "HTL", code: "4347" },
    { name: "RICE HOTEL HAVING UP TO 15 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "4346" },
    { name: "RICE HOTEL HAVING UP TO 15 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "4345" },
    { name: "RICE RETAIL", type: "GTL", code: "920" },
    { name: "RMC BRICKS,HUME PIPE", type: "ITL", code: "4334" },
    { name: "RUBBER GOODS MFG", type: "ITL", code: "4321" },
    { name: "SAND STONE BRICK ETC (OFFICE)", type: "GTL", code: "919" },
    { name: "SANITARY & HARDWARE", type: "GTL", code: "918" },
    { name: "SANITIZATION SERVICE PROVIDER", type: "GTL", code: "917" },
    { name: "SAW MILL", type: "ITL", code: "4190" },
    { name: "SCIENTIFIC ITEMS", type: "GTL", code: "916" },
    { name: "SCRAP PLASTIC CUTTING", type: "ITL", code: "4134" },
    { name: "SEAT HOOD COVER MANUFACTURE", type: "ITL", code: "4119" },
    { name: "SECURITY SERVICE PROVIDER", type: "GTL", code: "915" },
    { name: "SELF DRIVE BIKE AND CAR RENTALS", type: "GTL", code: "914" },
    { name: "SERVICING CENTER & MOTOR VEHICLE", type: "ITL", code: "4065" },
    { name: "SERVICING OF CAR", type: "ITL", code: "4063" },
    { name: "SEWING MACHINE (5 KW)", type: "ITL", code: "4057" },
    { name: "SHEET MFG", type: "ITL", code: "4046" },
    { name: "SHOE MFG", type: "ITL", code: "4040" },
    { name: "SKILL DEVELOPMENT TRAINING & PLACEMENT", type: "GTL", code: "913" },
    { name: "SMALL GROCERY SHOP", type: "STL", code: "747" },
    { name: "SODA/MINERAL WATER MFG", type: "ITL", code: "3974" },
    { name: "SOFT PVC PIPE MANUFACTURING", type: "ITL", code: "3968" },
    { name: "SOIL LABORATORY CUM OFFICE", type: "GTL", code: "912" },
    { name: "SPICES & CHOWMEIN MILL", type: "ITL", code: "3890" },
    { name: "STEEL ALMIRAH", type: "ITL", code: "3784" },
    { name: "STEEL ALUMINIUM(5 K.W)", type: "ITL", code: "3782" },
    { name: "STEEL AND PARTICLE BOARD FURNITURE", type: "ITL", code: "3778" },
    { name: "STEEL AND WOODEN FURNITURE", type: "ITL", code: "3777" },
    { name: "STEEL FABRICATION", type: "ITL", code: "3776" },
    { name: "STEEL FABRICATION WITH H.P 8 K.W", type: "ITL", code: "3775" },
    { name: "STEEL ITEM PAINT", type: "ITL", code: "3758" },
    { name: "STEEL TILES PROFILE MFG", type: "ITL", code: "3749" },
    { name: "STEEL TUBULAR POLES, TOWERS, STRUCTURALS", type: "ITL", code: "3747" },
    { name: "STONE CRUSHER", type: "ITL", code: "3728" },
    { name: "STONE CRUSHER MACHINE & SPARE PARTS", type: "GTL", code: "910" },
    { name: "SUPARI MFG AND PACKAGING", type: "ITL", code: "3702" },
    { name: "SUPARI RETAIL SALE", type: "GTL", code: "909" },
    { name: "SUSTAINABLE & WASTE MANAGEMENT OFFICE", type: "GTL", code: "908" },
    { name: "SWEET & CONFECTIONARY SUPPLY", type: "GTL", code: "907" },
    { name: "SWEET SHOP 16 SEATS TO 30 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "3541" },
    { name: "SWEET SHOP 16 SEATS TO 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "3540" },
    { name: "SWEET SHOP HAVING ABOVE 30 SEATS", type: "HTL", code: "3539" },
    { name: "SWEET SHOP HAVING UP TO 15 SEATS (AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "3538" },
    { name: "SWEET SHOP HAVING UP TO 15 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "3537" },
    { name: "SWIMMING POOL", type: "HTL", code: "3535" },
    { name: "TATTOO PARLOUR", type: "HTL", code: "3494" },
    { name: "TEA PACKAGING", type: "ITL", code: "3462" },
    { name: "TEA PACKAGING AND TEA CUP SALE", type: "ITL", code: "3458" },
    { name: "TEA STALL (AIR CONDITIONED ESTABLISHMENT WITH ANY SEATING CAPACITY)", type: "HTL", code: "3445" },
    { name: "TEA STALL (NON AIR CONDITIONED ESTABLISHMENT) NO SEATING ARRANGEMENT", type: "HTL", code: "3444" },
    { name: "TEA STALL HAVING 16 SEATS TO 30 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "3443" },
    { name: "TEA STALL HAVING ABOVE 30 SEATS", type: "HTL", code: "3442" },
    { name: "TEA STALL HAVING UP TO 15 SEATS (NON AIR CONDITIONED ESTABLISHMENT)", type: "HTL", code: "3441" },
    { name: "TEALEAF RETAIL", type: "GTL", code: "1000" },
    { name: "TELECOMMUNICATIONS", type: "GTL", code: "891" },
    { name: "TELEVISION & UTILITY SERVICES", type: "GTL", code: "882" },
    { name: "TENT HOUSE", type: "GTL", code: "878" },
    { name: "TEXTILES & APPAREL SERVICES", type: "GTL", code: "906" },
    { name: "THARMOCOL AND PVC", type: "ITL", code: "3374" },
    { name: "TILES & HARDWARE", type: "GTL", code: "905" },
    { name: "TIMBER OF MFG", type: "ITL", code: "3344" },
    { name: "TISSUE PAPER & TOILET ROLLS", type: "ITL", code: "3331" },
    { name: "TISSUE PAPER/ TOILET ROLL", type: "ITL", code: "3330" },
    { name: "TOUGHENED GLASS AND AUTOMOBILE GLASS", type: "ITL", code: "3313" },
    { name: "TRACTOR SERVICING", type: "ITL", code: "3272" },
    { name: "TRADER", type: "GTL", code: "880" },
    { name: "TRADITIONAL JEWELLERY & CLOTHING", type: "GTL", code: "887" },
    { name: "TRANSFORMER REPAIRING", type: "ITL", code: "3127" },
    { name: "TRANSFORMER REPAIRING AND MFG", type: "ITL", code: "3126" },
    { name: "TRANSPORTATION & LOGISTICS SERVICES", type: "GTL", code: "904" },
    { name: "TRAVEL AND TOURISM SERVICES", type: "GTL", code: "903" },
    { name: "TWO WHEELER REPAIRING CENTRE", type: "ITL", code: "2991" },
    { name: "TYRE REPAIRING", type: "ITL", code: "2973" },
    { name: "TYRE RETHREADING", type: "ITL", code: "2970" },
    { name: "TYRE RETREADING JAB (WORK SHOP) 43 KW", type: "ITL", code: "2969" },
    { name: "TYRE SALES", type: "GTL", code: "885" },
    { name: "UNISEX BEAUTY PARLOUR WITH SPA OR OTHER FACILITIES", type: "HTL", code: "2948" },
    { name: "UNISEX BEAUTY PARLOUR WITHOUT SPA OR OTHER FACILITIES", type: "HTL", code: "2947" },
    { name: "UNISEX SALON WITH SPA OR OTHER FACILITIES", type: "HTL", code: "2946" },
    { name: "UNISEX SALON WITHOUT SPA OR OTHER FACILITIES", type: "HTL", code: "2945" },
    { name: "UNISEX SPA SALON", type: "HTL", code: "2944" },
    { name: "UPS,STABILIZAR,INVATER AND TRANS FARMAR(10 KW)", type: "ITL", code: "2940" },
    { name: "UPVC WINDOW AND DOORS MFG", type: "ITL", code: "2937" },
    { name: "USED CAR & MOTOR CYCLE SHOW ROOM", type: "GTL", code: "901" },
    { name: "USED GOOD RETAIL & SECOND-HAND TRADE", type: "GTL", code: "900" },
    { name: "VEGETABLE RETAIL SALE", type: "GTL", code: "899" },
    { name: "VEGETABLE WHOLESALE", type: "GTL", code: "898" },
    { name: "WAREHOUSE", type: "GTL", code: "897" },
    { name: "WASTE MANAGEMENT OFFICE", type: "GTL", code: "896" },
    { name: "WATCH & CLOCK RETAIL & REPAIR SERVICES", type: "GTL", code: "895" },
    { name: "WEIGH BRIDGE", type: "ITL", code: "2815" },
    { name: "WELDING ELECTRODES AND BLACK WIRE", type: "ITL", code: "2804" },
    { name: "WHEAT AND SPICE PRODUCTION", type: "ITL", code: "2802" },
    { name: "WHOLESALE AND SUPPLY SERVICES", type: "GTL", code: "894" },
    { name: "WINE RETAIL SHOP", type: "GTL", code: "893" },
    { name: "WOOD & TIMBER SUPPLY & PRODUCTS", type: "GTL", code: "892" },
    { name: "WOOD DESIGNER", type: "ITL", code: "2743" },
    { name: "WOODEN FURNITURE", type: "ITL", code: "2732" },
    { name: "WORKSHOP", type: "ITL", code: "2715" },
    { name: "WORKSHOP 0 HP TO 4 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "2714" },
    { name: "WORKSHOP 0 HP TO 4 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "2713" },
    { name: "WORKSHOP 0 HP TO 4 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "2712" },
    { name: "WORKSHOP 0 HP TO 4 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "2711" },
    { name: "WORKSHOP 0 HP TO 4 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "2710" },
    { name: "WORKSHOP 0 HP TO 4 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "2709" },
    { name: "WORKSHOP 101 HP TO 250 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "2708" },
    { name: "WORKSHOP 101 HP TO 250 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "2707" },
    { name: "WORKSHOP 101 HP TO 250 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "2706" },
    { name: "WORKSHOP 101 HP TO 250 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "2705" },
    { name: "WORKSHOP 101 HP TO 250 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "2704" },
    { name: "WORKSHOP 101 HP TO 250 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "2703" },
    { name: "WORKSHOP 11 HP TO 19 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "2702" },
    { name: "WORKSHOP 11 HP TO 19 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "2701" },
    { name: "WORKSHOP 11 HP TO 19 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "2700" },
    { name: "WORKSHOP 11 HP TO 19 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "2699" },
    { name: "WORKSHOP 11 HP TO 19 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "2698" },
    { name: "WORKSHOP 11 HP TO 19 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "2697" },
    { name: "WORKSHOP 20 HP TO 100 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "2696" },
    { name: "WORKSHOP 20 HP TO 100 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "2695" },
    { name: "WORKSHOP 20 HP TO 100 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "2694" },
    { name: "WORKSHOP 20 HP TO 100 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "2693" },
    { name: "WORKSHOP 20 HP TO 100 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "2692" },
    { name: "WORKSHOP 20 HP TO 100 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "2691" },
    { name: "WORKSHOP 251 HP & ABOVE WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "2690" },
    { name: "WORKSHOP 251 HP & ABOVE WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "2689" },
    { name: "WORKSHOP 251 HP & ABOVE WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "2688" },
    { name: "WORKSHOP 251 HP & ABOVE WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "2687" },
    { name: "WORKSHOP 251 HP & ABOVE WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "2686" },
    { name: "WORKSHOP 251 HP & ABOVE WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "2685" },
    { name: "WORKSHOP 5 HP TO 10 HP WITH MANPOWER OF 1 TO 20 PERSONS", type: "HTL", code: "2684" },
    { name: "WORKSHOP 5 HP TO 10 HP WITH MANPOWER OF 101 TO 250 PERSONS", type: "HTL", code: "2683" },
    { name: "WORKSHOP 5 HP TO 10 HP WITH MANPOWER OF 21 TO 50 PERSONS", type: "HTL", code: "2682" },
    { name: "WORKSHOP 5 HP TO 10 HP WITH MANPOWER OF 251 TO 500 PERSONS", type: "HTL", code: "2681" },
    { name: "WORKSHOP 5 HP TO 10 HP WITH MANPOWER OF 501 & ABOVE PERSONS", type: "HTL", code: "2680" },
    { name: "WORKSHOP 5 HP TO 10 HP WITH MANPOWER OF 51 TO 100 PERSONS", type: "HTL", code: "2679" },
    { name: "YARN DRY AND DYING", type: "ITL", code: "2661" },
    { name: "YARN TWISTING AND PROCESSING UNIT", type: "ITL", code: "2659" },
    { name: "YOGA & MEDITATION CENTRE", type: "HTL", code: "2657" }
];
